name: My GitHub Action Workflow
on:
  workflow_dispatch:
    inputs:
      list_of_values:
        description: 'Enter a list of values (comma-separated)'
        required: true
      branch_name:
        description: 'Enter the name of the branch to switch to'
        required: true
 

jobs:
  list_of_values_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use the list of values input
        run: |
          list_of_values="${{ inputs.list_of_values }}"
          FS=',' read -ra values <<< "$list_of_values"
          
          # Now you have individual values in the 'values' array
          for value in "${values[@]}"; do
            echo "Value: $value"
          done

  switch_branch_job:
    runs-on: ubuntu-latest
    env: 
      BRANCH_NAME : ${{ github.event.inputs.branch_name }} 
    steps:
    - uses: actions/checkout@v1
      with:  
        ref: ${{ github.event.inputs.branch_name }}
    - name: Check
      run: |
          #echo -e 'Running on default: ${{ steps.branch-name.outputs.current_branch }}   
          echo -e 'var name: ${{ github.event.inputs.branch_name }}'
      
      # You can add further steps to make changes to the branch as needed.
